# Translation configuration settings
translation:
  # Target language for translation (ISO language code)
  target_language: "en"
  
  # Translation provider settings
  provider: "gemini"
  model: "gemini-2.0-flash"
  
  # Translation timing parameters
  interval: 3.0      # Minimum time between translation API calls (seconds)
  max_buffer_time: 10.0   # Maximum time to buffer text before forcing translation (seconds)
  inactivity_timeout: 2.0  # Seconds of inactivity before translating remaining buffer
  
  # Text processing settings
  min_text_length: 20      # Minimum text length to consider for translation (characters)