# Translation configuration settings
translation:
  # Target language for translation (ISO language code)
  target_language: "vi"
  
  # Translation provider settings
  provider: "gemini"
  model: "gemini-2.0-flash"
  
  # Translation timing parameters
  interval: 2.0      # Minimum time between translation API calls (seconds)
  max_buffer_time: 10.0   # Maximum time to buffer text before forcing translation (seconds)
  inactivity_timeout: 6.0  # Seconds of inactivity before translating remaining buffer
  
  # Text processing settings
  min_text_length: 10      # Minimum text length to consider for translation (characters)
  
  # Translation system prompt
  # Leave empty to use the default system prompt
  system_prompt: "Translate the following speech transcription into {target_language} in a natural, fluent way, ensuring clarity and readability. The content is about computers and programming, so use the natural language style commonly used by {target_language} tech professionals. Retain widely used English technical terms instead of translating them into {target_language}, unless a well-established {target_language} equivalent exists and is commonly used. Maintain the original meaning while ensuring the translation sounds natural and professional. Output only the translated text without any additional commentary or formatting."
